"use client";
import { useEffect, useRef, useState, type CSSProperties } from "react";
import { ArrowDownToLine, ArrowUp, ArrowDown, Check, ChevronRight, Copy, Download, Eye, FileUp, Grip, ImagePlus, Layers, LayoutTemplate, Minus, MousePointer2, Plus, Redo2, ShieldCheck, Smartphone, Square, Type, Undo2, Upload, X, Headphones, Settings2, Circle } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { initialProject, makeElement, parseProject, type ElementType, type DesignElement, type Project } from "@/lib/studio-model";
import { downloadProject, exportNative, previewHtml } from "@/lib/studio-export";

const types: {type:ElementType;label:string;icon:typeof Type}[] = [{type:"text",label:"Text",icon:Type},{type:"button",label:"Button",icon:MousePointer2},{type:"image",label:"Logo / image",icon:ImagePlus},{type:"shape",label:"Container",icon:Square},{type:"support",label:"Support",icon:Headphones},{type:"circle",label:"Circle",icon:Circle}];
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:[string,string][];label:string}) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>; }
function ColorField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) {return <label className="field"><span>{label}</span><div className="color-input"><input aria-label={label} type="color" value={value} onChange={e=>onChange(e.target.value)}/><span>{value.toUpperCase()}</span></div></label>}

export default function Studio() {
 const [project,setProject]=useState<Project>(initialProject),[selected,setSelected]=useState<string|null>("headline"),[tab,setTab]=useState("components"),[platform,setPlatform]=useState("android"),[zoom,setZoom]=useState(.72),[preview,setPreview]=useState(false),[exportOpen,setExportOpen]=useState(false),[busy,setBusy]=useState(false),[grid,setGrid]=useState(false),[saved,setSaved]=useState(false),[ready,setReady]=useState(false);
 const history=useRef<Project[]>([]),future=useRef<Project[]>([]),[,setRevision]=useState(0),projectRef=useRef(project),[assetMode,setAssetMode]=useState<"image"|"background">("image");
 const sdkPanel=useRef<HTMLDetailsElement>(null);
 const screen=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null),importInput=useRef<HTMLInputElement>(null);
 const drag=useRef<{id:string;x:number;y:number;ox:number;oy:number;w:number;h:number;resize:boolean}|null>(null);
 projectRef.current=project;
 const element=project.elements.find(e=>e.id===selected);
 function commit(next:Project){history.current.push(projectRef.current);if(history.current.length>60)history.current.shift();future.current=[];setProject(next);projectRef.current=next;setRevision(v=>v+1);}
 function patchElement(patch:Partial<DesignElement>){if(selected)commit({...project,elements:project.elements.map(e=>e.id===selected?{...e,...patch}:e)});}
 function undo(){const p=history.current.pop();if(p){future.current.push(projectRef.current);setProject(p);projectRef.current=p;setRevision(v=>v+1);}}
 function redo(){const p=future.current.pop();if(p){history.current.push(projectRef.current);setProject(p);projectRef.current=p;setRevision(v=>v+1);}}
 function add(type:ElementType,x=32,y=270){if(projectRef.current.elements.length>=150){toast.error("Maximum 150 elements per screen.");return;}const el=makeElement(type,x,y);commit({...projectRef.current,elements:[...projectRef.current.elements,el]});setSelected(el.id);}
 function remove(){if(!selected)return;commit({...project,elements:project.elements.filter(e=>e.id!==selected)});setSelected(null);}
 function duplicate(){if(!element||project.elements.length>=150)return;const el={...element,id:crypto.randomUUID(),x:clamp(element.x+16,0,390-element.w),y:clamp(element.y+16,0,844-element.h)};commit({...project,elements:[...project.elements,el]});setSelected(el.id);}
 function reorder(dir:number){const i=project.elements.findIndex(e=>e.id===selected),j=i+dir;if(i<0||j<0||j>=project.elements.length)return;const list=[...project.elements];[list[i],list[j]]=[list[j],list[i]];commit({...project,elements:list});}
 useEffect(()=>{try{const raw=localStorage.getItem("mobile-studio-project-v1");if(raw)setProject(parseProject(JSON.parse(raw)));}catch{toast.info("The local draft is unavailable. You can import a JSON project.");}if(window.innerWidth<700)setZoom(.65);setReady(true);},[]);
 useEffect(()=>{if(!ready)return;setSaved(false);const t=setTimeout(()=>{try{localStorage.setItem("mobile-studio-project-v1",JSON.stringify(project));setSaved(true);}catch{toast.error("Browser storage is full. Download the JSON project to keep your work.");}},450);return()=>clearTimeout(t);},[project,ready]);
 useEffect(()=>{function key(e:KeyboardEvent){const target=e.target as HTMLElement;if(target.closest("input,textarea,[contenteditable=true],[role=dialog],[role=combobox]"))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();if(e.shiftKey)redo();else undo();}else if(e.key==="Delete"||e.key==="Backspace"){e.preventDefault();remove();}else if(element&&["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)){e.preventDefault();const n=e.shiftKey?10:1;patchElement({x:clamp(element.x+(e.key==="ArrowRight"?n:e.key==="ArrowLeft"?-n:0),0,390-element.w),y:clamp(element.y+(e.key==="ArrowDown"?n:e.key==="ArrowUp"?-n:0),0,844-element.h)});}}window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);});
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!ctx)return;const life=new AbortController();try{Promise.resolve(ctx.registerTool({name:"read_mobile_design",description:"Read the current mobile design, element positions and export readiness.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({project:projectRef.current,androidBinary:"requires-build-runner-and-sdk-credentials",iosBinary:"requires-ios-sdk-integration-xcode-and-signing"})},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
 async function upload(file:File,mode:typeof assetMode,x=32,y=160){if(!["image/png","image/jpeg","image/webp"].includes(file.type)){toast.error("Choose a PNG, JPG or WebP image.");return;}if(file.size>8*1024*1024){toast.error("The image must be smaller than 8 MB.");return;}try{const bitmap=await createImageBitmap(file);const canvas=document.createElement("canvas");const factor=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*factor));canvas.height=Math.max(1,Math.round(bitmap.height*factor));canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const src=canvas.toDataURL("image/png");if(mode==="background"){commit({...projectRef.current,backgroundImage:src});setSelected(null);}else{if(projectRef.current.elements.length>=150)throw new Error();const base=makeElement("image",x,y);base.src=src;base.text=file.name.slice(0,1000);base.h=Math.max(24,Math.min(360,Math.round(base.w*canvas.height/canvas.width)));base.y=clamp(base.y,0,844-base.h);commit({...projectRef.current,elements:[...projectRef.current.elements,base]});setSelected(base.id);}toast.success(mode==="background"?"Background updated":"Image added");}catch{toast.error("Unable to read this image, or the element limit has been reached.");}}
 function chooseAsset(mode:typeof assetMode){setAssetMode(mode);fileInput.current?.click();}
 function template(name:string){commit(initialProject(name));setSelected("headline");toast.success("Template applied. You can undo this change.");}
 function pointerStart(ev:React.PointerEvent,id:string,resize=false){ev.stopPropagation();setSelected(id);const el=project.elements.find(e=>e.id===id)!;drag.current={id,x:ev.clientX,y:ev.clientY,ox:el.x,oy:el.y,w:el.w,h:el.h,resize};history.current.push(projectRef.current);if(history.current.length>60)history.current.shift();future.current=[];ev.currentTarget.setPointerCapture(ev.pointerId);}
 function pointerMove(ev:React.PointerEvent){const d=drag.current;if(!d)return;const dx=(ev.clientX-d.x)/zoom,dy=(ev.clientY-d.y)/zoom;const snap=(v:number)=>grid?Math.round(v/8)*8:Math.round(v);setProject(p=>({...p,elements:p.elements.map(el=>el.id!==d.id?el:{...el,...(d.resize?{w:clamp(snap(d.w+dx),24,390-d.ox),h:clamp(snap(d.h+dy),24,844-d.oy)}:{x:clamp(snap(d.ox+dx),0,390-el.w),y:clamp(snap(d.oy+dy),0,844-el.h)})})}));}
 function pointerEnd(){if(drag.current){drag.current=null;setRevision(v=>v+1);}}
 async function nativeExport(){setBusy(true);try{await exportNative(project,platform);toast.success("Source project downloaded");}catch(e){toast.error(e instanceof Error?e.message:"Export failed");}finally{setBusy(false);}}
 return <main className="studio"><Toaster richColors theme="light"/>
  <header className="topbar"><div className="brand"><span className="brand-symbol"><Layers size={21}/></span><strong>Teamviewer<span>Mobile Studio</span></strong><span className="beta">BETA</span></div><div className="project-identity"><input aria-label="Project name" value={project.name} maxLength={60} onChange={e=>commit({...project,name:e.target.value})}/><span className="save-state"><Check size={13}/>{saved?"Saved in this browser":"Local draft"}</span></div><div className="top-actions"><button className="quiet preview-button" onClick={()=>setPreview(true)}><Eye size={17}/>Preview</button><button className="primary" onClick={()=>setExportOpen(true)}><ArrowDownToLine size={17}/>Export<ChevronRight size={15}/></button></div></header>
  <div className="workspace">
   <aside className="left-panel"><Tabs value={tab} onValueChange={setTab}><TabsList className="panel-tabs"><TabsTrigger value="components">Elements</TabsTrigger><TabsTrigger value="templates">Template</TabsTrigger><TabsTrigger value="layers">Layers</TabsTrigger></TabsList>
    <TabsContent value="components"><section className="panel-section"><div className="section-heading"><h2>Add to canvas</h2><Plus size={16}/></div><p className="muted hint">Drag an element, or click to add.</p><div className="component-grid">{types.map(({type,label,icon:Icon})=><button key={type} className="component-tile" draggable onDragStart={e=>{e.dataTransfer.setData("application/studio-element",type);e.dataTransfer.effectAllowed="copy";}} onClick={()=>type==="image"?chooseAsset("image"):add(type)}><Icon size={25} strokeWidth={1.5}/><span>{label}</span></button>)}</div></section><section className="panel-section"><div className="section-heading"><h2>Your assets</h2><ImagePlus size={16}/></div><button className="upload-zone" onClick={()=>chooseAsset("image")} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])void upload(e.dataTransfer.files[0],"image");}}><Upload size={23}/><strong>Upload your logo</strong><span>PNG, JPG or WebP · max 8 MB</span></button><button className="wide quiet" onClick={()=>chooseAsset("background")}><ImagePlus size={16}/>Upload a background</button></section><section className="sdk-note"><span className="sdk-icon"><Headphones size={20}/></span><h3>Support, inside your app.</h3><p>Add a Support button and prepare your TeamViewer integration.</p><button onClick={()=>{if(sdkPanel.current){sdkPanel.current.open=true;sdkPanel.current.scrollIntoView({block:"nearest"});sdkPanel.current.querySelector("summary")?.focus();}}} className="text-button">Native build settings<ChevronRight size={14}/></button></section></TabsContent>
    <TabsContent value="templates"><section className="panel-section"><h2>A starting point.</h2><p className="muted hint">A template replaces the canvas. You can undo this.</p>{[["support","Essential support","#eef3ff","#255af6"],["dark","Midnight","#14233b","#79ecd2"],["clean","Minimal studio","#f5f6f8","#171c29"]].map(([name,label,bg,accent])=><button key={name} onClick={()=>template(name)} className="template-card"><div className="template-thumb" style={{background:bg}}><div style={{background:accent}}/><b style={{color:name==="dark"?"#fff":"#17233c"}}>Hello.<br/>Let’s connect.</b><span style={{background:accent}}/></div><span>{label}<ChevronRight size={15}/></span></button>)}</section></TabsContent>
    <TabsContent value="layers"><section className="panel-section"><div className="section-heading"><h2>Layers</h2><span className="count">{project.elements.length}</span></div><p className="muted hint">The first layers appear in front.</p><div className="layer-list">{[...project.elements].reverse().map(el=>{const Icon=types.find(t=>t.type===el.type)!.icon;return <button className={selected===el.id?"layer selected":"layer"} key={el.id} onClick={()=>setSelected(el.id)}><Icon size={16}/><span>{el.text||types.find(t=>t.type===el.type)!.label}</span><Grip size={14}/></button>})}<button className={!selected?"layer selected":"layer"} onClick={()=>setSelected(null)}><Square size={16}/>Background</button></div></section></TabsContent>
   </Tabs><div className="project-files"><button onClick={()=>downloadProject(project)}><Download size={15}/>Save JSON</button><button onClick={()=>importInput.current?.click()}><FileUp size={15}/>Open JSON</button></div></aside>
   <section className="canvas-area"><div className="canvas-toolbar"><div className="breadcrumb">Canvas<ChevronRight size={13}/><strong>Main screen</strong></div><div className="history-actions"><button className="icon-button" title="Undo (Ctrl+Z)" aria-label="Undo" disabled={!history.current.length} onClick={undo}><Undo2 size={17}/></button><button className="icon-button" title="Redo (Ctrl+Shift+Z)" aria-label="Redo" disabled={!future.current.length} onClick={redo}><Redo2 size={17}/></button><span className="divider"/><button className={`icon-button ${grid?"active":""}`} aria-label="Grid and snapping" title="Grid and snapping" onClick={()=>setGrid(!grid)}><Grip size={18}/></button></div></div>
    <div className="canvas-scroll"><div className="device-label"><Smartphone size={14}/>Mobile <span>390 × 844</span></div><div className="phone-space" style={{width:410*zoom,height:864*zoom}}><div className={`phone ${platform==="ios"?"ios":""}`} style={{transform:`scale(${zoom})`}}><div ref={screen} className={`phone-screen ${grid?"show-grid":""}`} style={{backgroundColor:project.background,backgroundImage:project.backgroundImage?`url(${project.backgroundImage})`:undefined,fontFamily:project.font}} onClick={()=>setSelected(null)} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="copy";}} onDrop={e=>{e.preventDefault();const rect=screen.current!.getBoundingClientRect();const x=(e.clientX-rect.left)/zoom,y=(e.clientY-rect.top)/zoom;if(e.dataTransfer.files[0]){void upload(e.dataTransfer.files[0],e.shiftKey?"background":"image",x,y);return;}const type=e.dataTransfer.getData("application/studio-element") as ElementType;if(types.some(t=>t.type===type))add(type,x,y);}}>
      <div className="phone-status" style={{color:project.statusColor}}><span>9:41</span><div className="camera"/><span>▮▮▮  ▰</span></div>
      {project.elements.map(el=><div role="button" tabIndex={0} aria-label={`Select ${el.text||el.type}`} key={el.id} className={`design-element ${selected===el.id?"is-selected":""}`} onKeyDown={e=>{if(e.key==="Enter")setSelected(el.id);}} style={{left:el.x,top:el.y,width:el.w,height:el.h,color:el.color,background:el.fill,fontSize:el.fontSize,fontWeight:el.bold?700:400,borderRadius:el.radius,textAlign:el.align,justifyContent:el.align==="left"?"flex-start":el.align==="right"?"flex-end":"center",opacity:el.opacity/100} as CSSProperties} onClick={e=>{e.stopPropagation();setSelected(el.id);}} onPointerDown={e=>pointerStart(e,el.id)} onPointerMove={pointerMove} onPointerUp={pointerEnd} onPointerCancel={pointerEnd}>
       {el.type==="image"?(el.src?<img src={el.src} alt={el.text} draggable={false} style={{objectFit:el.fit}}/>:<ImagePlus size={32}/>):<>{el.type==="support"&&<Headphones size={el.fontSize+3}/>}<span>{el.text}</span>{el.type==="support"&&<ChevronRight size={18}/>}</>}
       {selected===el.id&&<><div className="element-tag">{types.find(t=>t.type===el.type)!.label}</div><button aria-label="Resize element" className="resize-handle" onPointerDown={e=>pointerStart(e,el.id,true)} onPointerMove={pointerMove} onPointerUp={pointerEnd}/></>}
      </div>)}<div className="home-indicator" style={{background:project.statusColor}}/>
     </div></div></div><div className="canvas-tip"><MousePointer2 size={14}/>Move your elements. Make every detail yours.</div></div>
    <div className="canvas-footer"><span><span className="mini-dot"/>Screen 01</span><div className="zoom-controls"><button className="icon-button" aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.4,+(z-.1).toFixed(2)))}><Minus size={15}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(1.2,+(z+.1).toFixed(2)))}><Plus size={15}/></button></div><button className="text-button" onClick={()=>{setZoom(window.innerWidth<700?.65:.72);setSelected(null);}}>Fit</button></div>
   </section>
   <aside className="right-panel"><div className="inspector-heading"><Settings2 size={16}/><h2>Design</h2></div><details ref={sdkPanel} className="native-settings"><summary><ShieldCheck size={16}/><span>Native build settings</span><ChevronRight className="settings-chevron" size={16}/></summary><section className="panel-section"><div className="section-heading"><h2>In-app support</h2><Headphones size={18}/></div><p className="muted hint">The SDK adds remote support to your app. A native build produces an installable package.</p><div className="integration-status"><span className="amber-dot"/>Configuration required</div><label className="field"><span>Application / Bundle ID</span><input value={project.bundleId} onChange={e=>commit({...project,bundleId:e.target.value.slice(0,150)})} placeholder="com.example.support"/></label><label className="field"><span>Android SDK version</span><input value={project.sdkVersion} onChange={e=>commit({...project,sdkVersion:e.target.value.slice(0,40)})}/></label><div className="info-card"><strong>Android · ScreenSharing</strong><p>The project includes the native adapter and consent prompts. Configure the SDK token and repository credentials in your build environment.</p></div><div className="info-card"><strong>iOS · integration pending</strong><p>The project contains the interface and an integration boundary. Add the iOS SDK package and its documentation, then configure Xcode and Apple signing.</p></div><a className="text-button" href="https://teamviewer.github.io/TravelApp/ScreenSharingSdk/Sdk/index.html" target="_blank" rel="noreferrer">Official documentation<ChevronRight size={14}/></a><p className="tiny">Confirm licensing and SDK access with TeamViewer. This editor does not start remote sessions.</p></section></details><div className="design-properties">
    <section className="panel-section"><div className="section-heading"><h2>{element?types.find(t=>t.type===element.type)!.label:"Screen"}</h2>{element?<MousePointer2 size={16}/>:<Smartphone size={16}/>}</div>{element?<>
     <label className="field"><span>{element.type==="image"?"Image description":"Content"}</span><textarea value={element.text} maxLength={1000} rows={3} onChange={e=>patchElement({text:e.target.value})}/></label>
     <div className="section-label">POSITION AND SIZE</div><div className="numeric-grid">{([['x','X'],['y','Y'],['w','W'],['h','H']] as const).map(([key,label])=><label key={key}><span>{label}</span><input aria-label={label} type="number" value={element[key]} min={key==='w'||key==='h'?24:0} max={key==='x'||key==='w'?390:844} onChange={e=>{const v=Number(e.target.value);if(!Number.isFinite(v))return;patchElement(key==='x'?{x:clamp(v,0,390-element.w)}:key==='y'?{y:clamp(v,0,844-element.h)}:key==='w'?{w:clamp(v,24,390-element.x)}:{h:clamp(v,24,844-element.y)});}}/></label>)}</div>
     <div className="section-label">APPEARANCE</div><ColorField label="Text color" value={element.color} onChange={v=>patchElement({color:v})}/><ColorField label="Fill" value={element.fill==="transparent"?"#ffffff":element.fill} onChange={v=>patchElement({fill:v})}/><button className="text-button subtle" onClick={()=>patchElement({fill:"transparent"})}>Remove fill</button><div className="numeric-grid"><label><span>Radius</span><input aria-label="Radius" type="number" min={0} max={200} value={element.radius} onChange={e=>patchElement({radius:clamp(+e.target.value,0,200)})}/></label><label><span>Text</span><input aria-label="Font size" type="number" min={10} max={100} value={element.fontSize} onChange={e=>patchElement({fontSize:clamp(+e.target.value,10,100)})}/></label></div><label className="switch-row"><span>Bold</span><Switch checked={element.bold} onCheckedChange={v=>patchElement({bold:v})}/></label><label className="field"><span>Alignment</span><Choice label="Alignment" value={element.align} onChange={v=>patchElement({align:v as DesignElement['align']})} options={[["left","Left"],["center","Center"],["right","Right"]]}/></label>
     {element.type==="image"&&<label className="field"><span>Image fit</span><Choice label="Image fit" value={element.fit} onChange={v=>patchElement({fit:v as 'contain'|'cover'})} options={[["contain","Contain"],["cover","Cover"]]}/></label>}
     <div className="element-actions"><button aria-label="Bring forward" title="Bring forward" onClick={()=>reorder(1)}><ArrowUp size={16}/></button><button aria-label="Send backward" title="Send backward" onClick={()=>reorder(-1)}><ArrowDown size={16}/></button><button aria-label="Duplicate" title="Duplicate" onClick={duplicate}><Copy size={16}/></button><button aria-label="Delete" title="Delete" className="delete" onClick={remove}><X size={16}/></button></div>
    </>:<><p className="muted hint">Select an element on the phone to edit it.</p><ColorField label="Background color" value={project.background} onChange={v=>commit({...project,background:v})}/><button className="quiet wide" onClick={()=>chooseAsset("background")}><ImagePlus size={16}/>Choose an image</button>{project.backgroundImage&&<button className="text-button subtle" onClick={()=>commit({...project,backgroundImage:""})}>Remove background image</button>}<ColorField label="Status bar" value={project.statusColor} onChange={v=>commit({...project,statusColor:v})}/></>}</section>
    <section className="panel-section"><div className="section-heading"><h2>App style</h2><LayoutTemplate size={16}/></div><label className="field"><span>Font</span><Choice label="App font" value={project.font} onChange={v=>commit({...project,font:v as Project["font"]})} options={[["Manrope","Manrope"],["Arial","Arial"],["Georgia","Georgia"],["monospace","Monospace"]]}/></label><div className="font-preview" style={{fontFamily:project.font}}>Aa <span>{project.font}</span></div><button className="text-button" onClick={()=>setSelected(null)}>Edit background<ChevronRight size={14}/></button></section>
   </div></aside>
  </div>
  <input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0],assetMode);e.target.value="";}}/>
  <input ref={importInput} type="file" accept=".json,application/json" hidden onChange={async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;try{if(file.size>20*1024*1024)throw new Error("File too large");commit(parseProject(JSON.parse(await file.text())));setSelected(null);toast.success("Project imported");}catch{toast.error("Invalid file. Choose a JSON project exported by Teamviewer Mobile Studio.");}}}/>
  <Dialog open={preview} onOpenChange={setPreview}><DialogContent className="preview-dialog"><DialogHeader><DialogTitle>Interactive preview</DialogTitle><DialogDescription>Buttons illustrate the intended behavior. TeamViewer sessions require a configured native app.</DialogDescription></DialogHeader><iframe title="Mobile app preview" sandbox="allow-scripts allow-modals" srcDoc={previewHtml(project)} className="preview-iframe"/></DialogContent></Dialog>
  <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent className="export-dialog"><DialogHeader><div className="export-mark"><ArrowDownToLine size={24}/></div><DialogTitle>Bring your idea to mobile.</DialogTitle><DialogDescription>Export your project and prepare a native build.</DialogDescription></DialogHeader><Tabs value={platform} onValueChange={setPlatform}><TabsList className="export-platforms"><TabsTrigger value="android"><Smartphone size={17}/>Android</TabsTrigger><TabsTrigger value="ios"><Smartphone size={17}/>iOS</TabsTrigger></TabsList><TabsContent value="android"><div className="export-detail"><strong>Android project + TeamViewer</strong><span>Interface, images, fonts, Gradle, an SDK adapter and a build workflow.</span></div><div className="build-status"><span className="amber-dot"/><div><strong>APK: build service not connected</strong><p>An Android runner, SDK token and TeamViewer repository access are required. This download is a source ZIP, not an APK.</p></div></div></TabsContent><TabsContent value="ios"><div className="export-detail"><strong>SwiftUI project for Xcode</strong><span>Interface, images and fonts. Complete the TeamViewer integration using the supplied iOS SDK.</span></div><div className="build-status"><span className="amber-dot"/><div><strong>IPA: build service not connected</strong><p>The iOS SDK, macOS with Xcode, certificates and Apple provisioning are required. This download is a source ZIP, not a signed app.</p></div></div></TabsContent></Tabs><button className="primary wide export-download" onClick={nativeExport} disabled={busy}>{busy?"Preparing…":<><Download size={18}/>Download project {platform==="android"?"Android":"iOS"} (.zip)</>}</button><button className="quiet wide" onClick={()=>downloadProject(project)}><Copy size={16}/>Download editable design (.json)</button><p className="tiny">The project is generated in your browser. No credentials are requested here.</p></DialogContent></Dialog>
 </main>
}
